a.out:main.cpp
	g++ main.cpp -L/mnt/winshared/strtserver/product/Linux64/lib -ldl -lpthread -laps.base -laps.db -lUppResourceMgr -lDbEntity.strt -lUppMsgTransfer -lMsgCodec.XML.strt -lpchlfeeofsender -lpchlfeeofclient -laps.iconv -laps.gmp -lMQAgent -lUppMsgHandlerAPI -lUppMsgCustomHandlerAPI -lUppCommon -lMsgCodec.XML -lStrtAppUtils -limqc23gl_r -limqb23gl_r -lmqic_r -lmqiz_r -lmqmcs_r -lmqe_r -lmqecs_r -lmqxzu_r
#	g++ main.cpp -L/mnt/winshared/strtserver/product/Linux64/lib -ldl
