#!/bin/sh
FILENAME=$1
ORINUMBER=`grep "TRADID" $FILENAME | awk '{print $1}'`
NUMBER=${ORINUMBER:8:20}
NUMBER1=${NUMBER:12:8}
((NUMBER1=NUMBER1+1))
NUMBER1=${NUMBER:0:12}$NUMBER1
sed -i "s/$NUMBER/$NUMBER1/g" $FILENAME
exit




